sensors_db:
    host: sensors2.cy7n0vzxfedi.us-east-1.redshift.amazonaws.com
    port: 5439
    user: user
    password: password
    dbname: sensors1

anomaly_results_raw:
    host: localhost
    port: 5432
    user: 
    password: 
    dbname: 

anomaly_results:
    host: localhost
    port: 5432
    user: 
    password: 
    dbname: 

redis:
    host: localhost 
    port: 6379

dbscan_params:
    eps_multi: 1.0
    min_eps: 3.0
    min_pts: 5
    limit: 30
    limit_filter: 7
    alg_id: 1

