sensors_db:
    host: sensors2.cy7n0vzxfedi.us-east-1.redshift.amazonaws.com
    port: 5439
    user: user
    password: password
    dbname: sensors1

anomaly:
    host: localhost
    port: 5432
    user: 
    password: 
    dbname: 

redis:
    host: localhost 
    port: 6379

dbscan_params_meta:
    dbscan_params_1:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 7 
        alg_id: 1
    dbscan_params_2:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 30 
        alg_id: 2
    dbscan_params_3:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 29 
        alg_id: 3

