sensors_db:
    host: sensors2.cy7n0vzxfedi.us-east-1.redshift.amazonaws.com
    port: 5439
    user: user
    password: password
    dbname: sensors1

anomaly:
    host: localhost
    port: 5432
    user: 
    password: 
    dbname: 

dbscan_params_meta:
    dbscan_params_1:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 7 
        alg_id: 1
        max_anom_density: 99 
        insert_question: False
        sensor: light
    dbscan_params_2:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 20 
        alg_id: 4
        max_anom_density: 3 
        insert_question: True
        sensor: light
    dbscan_params_3:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 29 
        alg_id: 3
        max_anom_density: 99 
        insert_question: False
        sensor: light

redis:
    host: localhost
    port: 6379

questions_endpt_params:
    url: http://localhost:5678/v1/questions/anomaly
    authorization: 
    content-type: application/json

