sensors_db:
    host: sensors2.cy7n0vzxfedi.us-east-1.redshift.amazonaws.com
    port: 5439
    user: user
    password: password
    dbname: sensors1

anomaly_results:
    host: localhost
    port: 5432
    dbname: 

redis:
    host: stats.xoe7je.0001.use1.cache.amazonaws.com
    port: 6379
