common_db:
    host: 
    port: 5432
    user: 
    password: 
    dbname: 

sensors_db:
    host: sensors-2-replica-1.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432
    user: sensors
    port: 5432
    password: hello-sensors
    dbname: sensors1

anomaly:
    host: 
    port: 5432
    user: 
    password: 
    dbname: 

redis:
    host: stats.xoe7je.0001.use1.cache.amazonaws.com
    port: 6379

dbscan_params:
    eps_multi: 1.0
    min_eps: 3.0
    min_pts: 5
    limit: 30
    limit_filter: 7
    max_density: 30 
    alg_id: 1

questions:
    question_id: 33
    days_on: 1

