sensors_db:
    host: sensors2.cy7n0vzxfedi.us-east-1.redshift.amazonaws.com
    user: anomaly
    port: 5439
    password: Hello-anomaly123
    dbname: sensors1
    connect_timeout: 3

anomaly:
    host: research.cdawj8qazvva.us-east-1.rds.amazonaws.com
    port: 5432
    user: research_user
    password: hello-research-user
    dbname: research
    connect_timeout: 3

dbscan_params_meta:
    dbscan_params_2:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 20 
        alg_id: 4
        max_anom_density: 3 
        insert_question: True
        sensor: light

redis:
    host: stats-002.xoe7je.0001.use1.cache.amazonaws.com
    port: 6379

questions_endpt_params:
    url: https://admin-api.hello.is/v1/questions/anomaly

