sensors_db:
    host: sensors-2-replica-1.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432
    user: sensors
    port: 5432
    password: hello-sensors
    dbname: sensors1

anomaly_results:
    host: 
    port: 5432
    dbname: 

redis:
    host: stats.xoe7je.0001.use1.cache.amazonaws.com
    port: 6379
