sensors_db:
    host: sensors-2-replica-1.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432
    user: sensors
    port: 5432
    password: hello-sensors
    dbname: sensors1

anomaly:
    host: 
    port: 5432
    user: 
    password: 
    dbname: 

redis:
    host: 
    port: 6379

dbscan_params_meta:
    dbscan_params_2:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 20 
        alg_id: 4
        max_anom_density: 3 
        insert_question: True
        sensor: light

redis:
    host: 
    port: 

questions_endpt_params:
    url: https://dev-admin.hello.is
