sensors_db:
    host: sensors-2-replica-1.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432
    user: sensors
    port: 5432
    password: hello-sensors
    dbname: sensors1

anomaly:
    host: 
    port: 5432
    user: 
    password: 
    dbname: 

redis:
    host: 
    port: 6379

dbscan_params_meta:
    dbscan_params_1:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 7 
        alg_id: 1
        max_anom_density: 99 
        insert_question: False
        sensor: light
    dbscan_params_2:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 20 
        alg_id: 4
        max_anom_density: 3 
        insert_question: True
        sensor: light
    dbscan_params_3:
        eps_multi: 1.0
        min_eps: 3.0
        min_pts: 5
        limit_filter: 29 
        alg_id: 3
        max_anom_density: 99 
        insert_question: False
        sensor: light

redis:
    host: 
    port: 

questions_endpt_params:
    url: https://dev-admin.hello.is
    authorization: 'Bearer: 25.74df3bb1a86b490e835e874760d96890'
    content-type: application/json
